name: Deploy AWSense
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # -------------------------
      # FRONTEND BUILD
      # -------------------------

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v7
        with:
          name: frontend-dist
          path: frontend/dist

      # -------------------------
      # BACKEND PACKAGE
      # -------------------------

      - name: Create Lambda package
        working-directory: backend
        run: |
          zip -r lambda.zip src/ requirements.txt

      - name: Upload Lambda artifact
        uses: actions/upload-artifact@v7
        with:
          name: lambda-package
          path: backend/lambda.zip

  integration-test:
  needs: [build]
  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install backend dependencies
      working-directory: backend
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run integration tests
      working-directory: backend
      run: |
        pytest tests/integration -v