name: Deploy AWSense
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # -------------------------
      # FRONTEND BUILD
      # -------------------------

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_API_KEY: ${{ secrets.API_KEY }}
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v7
        with:
          name: frontend-dist
          path: frontend/dist


      # txt files generation + faiss index generation
      - name: Setup Python (for vector build)
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install vector build dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt
          pip install sentence-transformers faiss-cpu numpy beautifulsoup4 requests 


      - name: Generate AWS docs dataset
        run: |
          python scripts/awsdocs_collector_metadata_generator.py

      - name: Build FAISS vector store
        run: |
          python scripts/build_vector_store.py

      # in case build_vector_store.py fails to save the index, this will help debug
      - name: Verify vector store exists
        run: |
          ls -R backend/vector_store
          test -f backend/vector_store/awsense.index

      # -------------------------
      # BACKEND PACKAGE
      # -------------------------

      # we only need the vector_store folder in future and the remaining code already
      # exists in the repo also infra_stack is going to package the contents of backend folder it does not need a separate zip package for the backend code.

      # VECTOR STORE ARTIFACT
      - name: Upload vector store artifact
        uses: actions/upload-artifact@v7
        with:
          name: vector-store
          path: backend/vector_store/

  integration-test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run integration tests
        working-directory: backend
        run: |
          pytest tests/integration -v
  
  deploy:
    needs: [integration-test]
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
      API_KEY: ${{ secrets.API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # -------------------------
      # RESTORE VECTOR STORE
      # -------------------------
      - name: Download vector store artifact
        uses: actions/download-artifact@v7
        with:
          name: vector-store
          path: backend/vector_store

      # -------------------------
      # SETUP NODE (for CDK CLI)
      # -------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install CDK
        run: npm install -g aws-cdk

      # -------------------------
      # SETUP PYTHON
      # -------------------------
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # -------------------------
      # INSTALL LAMBDA DEPENDENCIES
      # -------------------------
      - name: Install python_packages
        working-directory: backend
        run: |
          pip install -r requirements.txt -t python_packages

      # -------------------------
      # INSTALL CDK DEPENDENCIES
      # -------------------------
      - name: Install infra dependencies
        working-directory: infra
        run: |
          pip install -r requirements.txt

      # download frontend artifact for cdk packaging
      - name: Download frontend artifact
        uses: actions/download-artifact@v7
        with:
          name: frontend-dist
          path: frontend/dist

      # final verification of the artifacts before cdk packaging
      - name: Verify deployment assets
        run: |
          test -f backend/vector_store/awsense.index
          test -f backend/vector_store/documents.pkl
          test -d backend/python_packages
          test -f frontend/dist/index.html


      - name: Bootstrap CDK
        run: |
          cd infra
          cdk bootstrap

      # -------------------------
      # DEPLOY CDK STACK
      # -------------------------
      - name: Deploy CDK
        run: |
          cd infra
          cdk deploy --require-approval never
      
